"""Prepare a separate binary ImageFolder dataset; never modify source images."""

import argparse
import json
import shutil
from pathlib import Path

MARKER = ".retrieval-generated.json"
OWNER = "retrieval.tip_adapter.preprocessing"
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".gif", ".tif", ".tiff"}


def process_dataset(source_dir, target_dir, keep_classes, overwrite=False):
    """Map one target class to 0 and other classes to 1 in train/val.

    Source layout: source/{train,val}/{class_name}/images.
    Only output previously generated by this function may be overwritten.
    All source checks precede replacement of existing generated output.
    """
    source = Path(source_dir).expanduser().resolve()
    destination_input = Path(target_dir).expanduser()
    if destination_input.is_symlink():
        raise ValueError("The generated dataset directory must not be a symlink.")
    target = destination_input.resolve()
    if source == target or source in target.parents or target in source.parents:
        raise ValueError("Source and output must be separate, non-nested paths.")
    classes = [keep_classes] if isinstance(keep_classes, str) else list(keep_classes)
    if len(classes) != 1:
        raise ValueError("This experiment requires exactly one target class.")
    selected = str(classes[0])
    if not selected or selected in {".", ".."} or "/" in selected or "\\" in selected:
        raise ValueError("The target class must be a single folder name.")

    plan = []
    counts = {}
    for split in ("train", "val"):
        split_dir = source / split
        if not split_dir.is_dir():
            raise FileNotFoundError(f"Missing source split: {split_dir}")
        counts[split] = [0, 0]
        for class_dir in sorted(split_dir.iterdir()):
            if not class_dir.is_dir() or class_dir.name.startswith("."):
                continue
            if class_dir.is_symlink():
                raise ValueError(f"Source class must not be a symlink: {class_dir}")
            label = 0 if class_dir.name == selected else 1
            for image in sorted(class_dir.rglob("*")):
                if any(part.startswith(".") for part in image.relative_to(class_dir).parts):
                    continue
                if image.is_symlink():
                    raise ValueError(f"Source image must not be a symlink: {image}")
                if not image.is_file() or image.suffix.lower() not in IMAGE_EXTENSIONS:
                    continue
                relative = Path(split) / str(label) / class_dir.name / image.relative_to(class_dir)
                plan.append((image, relative))
                counts[split][label] += 1
        if not all(counts[split]):
            raise ValueError(
                f"{split} needs positive images in '{selected}' and negative images "
                f"in other class folders; found {counts[split]}. See DATASET.md."
            )

    if target.exists():
        if not target.is_dir():
            raise FileExistsError(f"Output path is not a directory: {target}")
        if any(target.iterdir()):
            if not overwrite:
                raise FileExistsError(f"Output already contains files: {target}; use --overwrite explicitly.")
            marker = target / MARKER
            try:
                owned = not marker.is_symlink() and json.loads(marker.read_text()).get("owner") == OWNER
            except (OSError, ValueError, AttributeError):
                owned = False
            if not owned:
                raise ValueError("Refusing to overwrite a directory not created by this tool.")
            shutil.rmtree(target)

    target.mkdir(parents=True, exist_ok=True)
    for image, relative in plan:
        output = target / relative
        output.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(image, output)
    (target / MARKER).write_text(
        json.dumps({"owner": OWNER, "target_class": selected, "counts": counts}, indent=2) + "\n"
    )
    print(f"Prepared {len(plan)} image files in {target}; source files unchanged.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source_dir", required=True, help="Source with train/val class folders")
    parser.add_argument("--target_dir", required=True, help="Separate generated output directory")
    parser.add_argument("--keep_classes", nargs="+", required=True, help="Exactly one target folder name")
    parser.add_argument("--overwrite", action="store_true", help="Replace previously generated output")
    args = parser.parse_args()
    process_dataset(args.source_dir, args.target_dir, args.keep_classes, args.overwrite)


if __name__ == "__main__":
    main()
